# Generated by Django 3.2 on 2021-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('OpenID', models.CharField(max_length=50)),
                ('Icon', models.CharField(max_length=200)),
                ('RealName', models.CharField(max_length=50)),
                ('NickName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
            },
        ),
    ]
