# Generated by Django 3.2 on 2021-04-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Account', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('Power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('OpenID', models.CharField(max_length=50)),
                ('Icon', models.CharField(max_length=200)),
                ('RealName', models.CharField(max_length=50)),
            ],
        ),
    ]
