# Generated by Django 3.2 on 2021-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Role',
            field=models.IntegerField(default=0),
        ),
    ]
