# Generated by Django 3.2 on 2021-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Telephone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
