# Generated by Django 3.2.2 on 2021-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210507_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='RealName',
            field=models.CharField(default='', max_length=50, verbose_name='商户信息'),
        ),
    ]
