# Generated by Django 3.2.2 on 2021-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_alter_goodinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='Company',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='单位'),
        ),
    ]
